config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("posts/", include("posts.urls", namespace="posts")),
    path("users/", include("users.urls", namespace="users")),
    path("comments/", include("comments.urls", namespace="comments")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from posts import views as post_views

app_name = "core"

urlpatterns = [
    # path("", post_views.all_posts, name="home"),
    path("", post_views.HomeView.as_view(), name="home"),
]

posts/urls.py
from django.urls import path
from . import views as post_views

app_name = "posts"

urlpatterns = [
    path("add/", post_views.AddPostView.as_view(), name="add"),
    path("<int:pk>", post_views.post_detail, name="detail"),
    path("<int:pk>/edit/", post_views.EditPostView.as_view(), name="edit"),
    path("<int:pk>/delete/", post_views.post_delete, name="delete"),
    path("<int:pk>/photos/", post_views.PostPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add/", post_views.AddPhotoView.as_view(), name="add-photo"),
    path(
        "<int:post_pk>/photos/<int:photo_pk>/delete/",
        post_views.delete_photo,
        name="delete-photo",
    ),
    path(
        "<int:post_pk>/photos/<int:photo_pk>/edit/",
        post_views.EditPhotoView.as_view(),
        name="edit-photo",
    ),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
]

posts/models.py
import os
from datetime import datetime, timedelta, timezone

from django.db import models
from django.db.models.signals import post_delete, pre_save
from django.dispatch import receiver
from django.urls import reverse

from core import models as core_models
from users import models as user_models


class Photo(core_models.TimeStampedModel):

    """Photo Model Definition"""

    caption = models.CharField(max_length=80)
    file = models.ImageField(upload_to="post_photos")
    post = models.ForeignKey("Post", related_name="photos", on_delete=models.CASCADE)

    def __str__(self):
        return self.caption


@receiver(post_delete, sender=Photo)
def file_delete_action(sender, instance, **kwargs):
    instance.file.delete(False)


@receiver(pre_save, sender=Photo)
def file_update_action(sender, instance, **kwargs):
    if not instance.pk:
        return False
    try:
        old_obj = sender.objects.get(pk=instance.pk)
    except sender.DoesNotExist:
        return False

    for field in instance._meta.fields:
        field_type = field.get_internal_type()
        if field_type == "FileField" or field_type == "ImageField":
            origin_file = getattr(old_obj, field.name)
            new_file = getattr(instance, field.name)
            print(origin_file, new_file)
            if origin_file != new_file and os.path.isfile(origin_file.path):
                os.remove(origin_file.path)


class Post(core_models.TimeStampedModel):

    """Post Model Definition"""

    author = models.ForeignKey(user_models.User, on_delete=models.CASCADE)
    title = models.TextField()
    content = models.TextField()

    def __str__(self):
        return f"{self.title} - {self.author}"

    # TODO
    def comments_count(self):
        commentCount = self.post_comments.count()
        return int(commentCount)

    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"pk": self.pk})

    def first_photo(self):
        try:
            (photo,) = self.photos.all()[:1]
            return photo.file.url
        except ValueError:
            return None

    def created_string(self):
        created_time = datetime.now(tz=timezone.utc) - self.created

        if created_time < timedelta(minutes=1):
            return "Just before"
        elif created_time < timedelta(hours=1):
            return str(int(created_time.seconds / 60)) + " minutes ago"
        elif created_time < timedelta(days=1):
            return str(int(created_time.seconds / 3600)) + " hours ago"
        else:
            created_time = datetime.now(tz=timezone.utc).date() - self.created.date()
            return str(created_time.days) + " days ago"

posts/forms.py
from django import forms
from .models import Photo, Post
from users.models import User


class AddPhotoForm(forms.ModelForm):

    """AddPhotoForm Definition"""

    class Meta:
        model = Photo
        fields = (
            "file",
            "caption",
        )

    def save(self, pk, *args, **kwargs):
        photo = super().save(commit=False)
        post = Post.objects.get(pk=pk)
        photo.post = post
        photo.save()


class AddPostForm(forms.ModelForm):

    """AddPostForm Definition"""

    class Meta:
        model = Post
        fields = (
            "title",
            "content",
        )

    def save(self, user_pk, *args, **kwargs):
        post = super().save(commit=False)
        author = User.objects.get(pk=user_pk)
        post.author = author
        post.save()
        return post

posts/views.py
# from django.core.paginator import Paginator, EmptyPage
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.http.response import Http404
from django.shortcuts import redirect, render, reverse
from django.views.generic import DetailView, FormView, ListView, UpdateView

from users import mixins as user_mixins

from . import models as post_models
from .forms import AddPhotoForm, AddPostForm


class HomeView(ListView):

    """HomeView Definition"""

    model = post_models.Post
    paginate_by = 10
    paginate_orphans = 5
    ordering = "-created"
    context_object_name = "posts"


class AddPostView(user_mixins.LoggedInOnlyView, FormView):

    """AddPostView Definition"""

    template_name = "posts/post_add.html"
    form_class = AddPostForm

    def form_valid(self, form):
        user_pk = self.request.user.pk
        post = form.save(user_pk)
        messages.success(self.request, "Post Uploaded!")
        return redirect(reverse("posts:detail", kwargs={"pk": post.pk}))


def post_detail(request, pk):
    try:
        post = post_models.Post.objects.get(pk=pk)
        return render(request, "posts/detail.html", context={"post": post})
    except post_models.Post.DoesNotExist:
        return redirect("core:home")


class EditPostView(user_mixins.LoggedInOnlyView, UpdateView):

    """EditPostView Definition"""

    model = post_models.Post
    template_name = "posts/post_edit.html"
    fields = (
        "title",
        "content",
    )

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        messages.success(self.request, "Post Updated!")
        return super().post(request, *args, **kwargs)

    def get_object(self, queryset=None):
        post = super().get_object(queryset=queryset)
        if post.author.pk != self.request.user.pk:
            raise Http404()
        return post


@login_required
def post_delete(request, pk):
    """Post Delete Definition"""

    try:
        post = post_models.Post.objects.get(pk=pk)
        if post.author.pk != request.user.pk:
            messages.error(request, "Can't delete that post")
        else:
            post.delete()
            messages.success(request, "Post Deleted!")
            return redirect(reverse("core:home"))
    except post_models.Post.DoesNotExist:
        return redirect("core:home")


class PostPhotosView(user_mixins.LoggedInOnlyView, DetailView):

    """RoomPhotosView Definition"""

    model = post_models.Post
    template_name = "posts/post_photos.html"

    def get_object(self, queryset=None):
        post = super().get_object(queryset=queryset)
        if post.author.pk != self.request.user.pk:
            raise Http404()
        return post


@login_required
def delete_photo(request, post_pk, photo_pk):
    """Delete Photo Definition"""

    user = request.user
    try:
        post = post_models.Post.objects.get(pk=post_pk)
        if post.author.pk != user.pk:
            messages.error(request, "Can't delete that photo")
        else:
            post_models.Photo.objects.filter(pk=photo_pk).delete()
            messages.success(request, "Photo Deleted!")
        return redirect(reverse("posts:photos", kwargs={"pk": post_pk}))
    except post_models.Post.DoesNotExist:
        return redirect(reverse("core:home"))


class EditPhotoView(user_mixins.LoggedInOnlyView, SuccessMessageMixin, UpdateView):

    """PhotoEditView Definition"""

    model = post_models.Photo
    template_name = "posts/photo_edit.html"
    pk_url_kwarg = "photo_pk"
    success_message = "Photo Updated!"
    fields = (
        "file",
        "caption",
    )

    def get_success_url(self):
        post_pk = self.kwargs.get("post_pk")
        return reverse("posts:photos", kwargs={"pk": post_pk})


class AddPhotoView(user_mixins.LoggedInOnlyView, FormView):

    """AddPhotoView Definition"""

    template_name = "posts/photo_add.html"
    form_class = AddPhotoForm

    def form_valid(self, form):
        pk = self.kwargs.get("pk")
        form.save(pk)
        messages.success(self.request, "Photo Uploaded!")
        return redirect(reverse("posts:photos", kwargs={"pk": pk}))


""" def all_posts(request):
    page = request.GET.get("page", 1)
    post_list = post_models.Post.objects.all()
    paginator = Paginator(post_list, 10, orphans=5)
    try:
        posts = paginator.page(int(page))
        return render(request, "posts/home.html", context={"posts": posts})
    except EmptyPage:
        return redirect("/") """


""" def all_posts(request):
    page = request.GET.get("page", 1)
    page = int(page or 1)
    page_size = 10
    limit = page_size * page
    offset = limit - page_size
    page_count = ceil(post_models.Post.objects.count() / page_size)
    all_posts = post_models.Post.objects.all()[offset:limit]
    return render(
        request,
        "posts/home.html",
        context={
            "posts": all_posts,
            "page": page,
            "page_count": page_count,
            "page_range": range(1, page_count + 1),
        },
    ) """

templates/posts/detail.html
{% extends 'base.html' %}
    {% block contents %}
    <div class="px-20">
        <div class="flex justify-between items-center border-b-2 px-3 mt-20 pb-2">
            <div>
                <span class="font-medium text-2xl">{{post.title}}</span>
                <span class="text-lg">| By :<a href="{% url 'users:profile' post.author.pk %}" class="text-blue-400">{{post.author.first_name}}</a></span>
            </div>
            <span>{{post.created_string}}</span>
        </div>
        <div class="my-20 py-2 relative">

            {% if post.author == user %}
                <a href="{% url 'posts:edit' pk=post.pk %}">
                    <span class="absolute block -mt-20 ml-3 py-1 px-2 font-medium text-lg border-2 rounded-lg border-yellow-400 bg-yellow-400 text-white">Edit</span>
                </a>
                <a href="{% url 'posts:delete' pk=post.pk %}">
                    <span class="absolute block -mt-20 ml-20 py-1 px-2 font-medium text-lg border-2 rounded-lg border-red-600 bg-red-400 text-white">Delete</span>
                </a>
            {% endif %}

            <div class="flex justify-center">
                {% for photo in post.photos.all %}
                    <img class="ml-2" width="200px" src="{{photo.file.url}}" />
                {% endfor %}
            </div>
            <div class="text-center mt-5 px-20">
                {{post.content}}
            </div>
        </div>
        {% include 'comments/comment_list.html' with comments=post.post_comments.all post_pk=post.pk %}
    </div>
    {% endblock contents %}

templates/posts/photo_add.html
{% extends 'base.html' %}
    {% block contents %}
        <div class="p-6 container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border border-gray-400">
            {% include 'mixins/post/post_form.html' with form=form cta="Add Photo" %}
        </div>
    {% endblock contents %}
        

templates/posts/photo_edit.html
{% extends 'base.html' %}
    {% block contents %}
        <div class="p-6 container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border border-gray-400">
            {% include 'mixins/post/post_form.html' with form=form cta="Update Photo" %}
        </div>
    {% endblock contents %}
        

templates/posts/post_add.html
{% extends 'base.html' %}
    {% block contents %}
        <div class="p-6 container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border border-gray-400">
            {% include 'mixins/post/post_form.html' with form=form cta="Add Post" %}
        </div>
    {% endblock contents %}
        

templates/posts/post_edit.html
{% extends 'base.html' %}
    {% block contents %}
        <div class="p-6 container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border border-gray-400">
            {% include 'mixins/post/post_form.html' with form=form cta="Update Room" %}
            <div class="mt-3 btn border-2 bg-indigo-400 text-white font-medium text-xl">
                <a href="{% url 'posts:add-photo' pk=post.pk %}">Add Photos</a>
            </div>
            <div class="mt-3 btn border-2 bg-green-400 text-white font-medium text-xl">
                <a href="{% url 'posts:photos' pk=post.pk %}">Change Photos</a>
            </div>
        </div>
    {% endblock contents %}
        

templates/posts/post_list.html
{% extends "base.html" %}

    {% block page_title %}
        Home
    {% endblock page_title %}

    {% block contents %}
    <div class="flex flex-col px-20 my-5 items-center relative">
        {% for post in posts %}
            <div class="w-3/5 border-b mb-5 py-6 flex items-center justify-between">
                <div class="w-4/5">
                    <a href="{% url 'posts:detail' post.pk %}">
                        <div class="flex items-center mb-3">
                            {% include "mixins/user_avartar.html" with user=post.author h_and_w='w-10 h-10' %}
                            <div class="ml-5">
                                <span class="text-lg block">{{post.author.first_name}}</span>
                                <span>{{post.created|date:'F Y'}}</span>
                            </div>
                        </div>
                        <span class="text-3xl font-medium block mb-5">{{post.title}}</span>
                        <p class="text-lg">
                            {{post.content}}
                        </p>
                        <span class="text-gray-500 block mt-6">comment {{post.comments_count}}</span>
                    </a>
                </div>
                <div class="w-1/5">
                    <img class="block right-0" width="250px" src="{{post.first_photo}}" />
                </div>
            </div>
        {% endfor %}

        <div class="py-5 text-center flex items-center justify-center">
            {% if page_obj.has_previous %}
                <a href="?page={{page_obj.previous_page_number}}" class="text-green-600"><i class="fas fa-arrow-left fa-lg"></i></a>
            {% endif %}

            <span class="text-2xl font-medium mx-3">
                {{page_obj.number}} of {{page_obj.paginator.num_pages}}
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{page_obj.next_page_number}}" class="text-green-600"><i class="fas fa-arrow-right fa-lg"></i></a>
            {% endif %}

            <!--{% for page in page_range %}
                <a href="?page={{page}}">{{page}}</a>
            {% endfor %}-->
        </div>
    </div>
    {% endblock contents %}

templates/posts/post_photos.html
{% extends 'base.html' %}
    {% block contents %}
        <div class="container mx-auto my-10 flex flex-col items-center w-full">
            {% for photo in post.photos.all %}
                <div class="border-2 mt-5 flex justify-between rounded-2xl p-3 w-1/4">
                    <div class="flex flex-col items-center w-1/2">
                        <img src="{{photo.file.url}}" class="w-32 h-32" />
                        <span class="text-light text-lg mt-2">{{photo.caption}}</span>
                    </div>
                    <div class="flex flex-col justify-center ml-2 w-1/2">
                        <a href="{% url 'posts:edit-photo' post.pk photo.pk %}" class="btn border-2 w-full font-medium py-2 bg-yellow-400 text-white">Edit</a >
                        <a href="{% url 'posts:delete-photo' post.pk photo.pk %}" class="btn border-2 w-full font-medium py-2 mt-2 bg-green-400 text-white">Delete</a >
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endblock contents %}
        