config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("posts/", include("posts.urls", namespace="posts")),
    path("users/", include("users.urls", namespace="users")),
    path("comments/", include("comments.urls", namespace="comments")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from posts import views as post_views

app_name = "core"

urlpatterns = [
    # path("", post_views.all_posts, name="home"),
    path("", post_views.HomeView.as_view(), name="home"),
]

posts/urls.py
from django.urls import path
from . import views as post_views

app_name = "posts"

urlpatterns = [
    path("add/", post_views.AddPostView.as_view(), name="add"),
    path("<int:pk>", post_views.post_detail, name="detail"),
    path("<int:pk>/edit/", post_views.EditPostView.as_view(), name="edit"),
    path("<int:pk>/delete/", post_views.post_delete, name="delete"),
    path("<int:pk>/photos/", post_views.PostPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add/", post_views.AddPhotoView.as_view(), name="add-photo"),
    path(
        "<int:post_pk>/photos/<int:photo_pk>/delete/",
        post_views.delete_photo,
        name="delete-photo",
    ),
    path(
        "<int:post_pk>/photos/<int:photo_pk>/edit/",
        post_views.EditPhotoView.as_view(),
        name="edit-photo",
    ),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
]

templates/partials/footer.html
<div class="w-full text-center border-t-2 py-4">
    <span class="text-gray-500 font-medium text-lg">Buzurgmexr's blog site</span>
</div>

templates/partials/header.html
<header class="w-full flex justify-between px-10 py-5 items-center">
    <div class="w-1/3"></div>
    <a href="{% url 'core:home' %}" class="font-bold text-8xl"><h1>Blogs</h1></a>
    <ul class="w-1/3 flex text-3xl justify-end items-centerx">
        {% if user.is_authenticated %}
            <li class="nav_li"><a href="{% url 'posts:add' %}">Writing</a></li>
            <li class="nav_li ml-6"><a href="{% url 'users:profile' user.pk %}">Profile</a></li>
            <li class="nav_li ml-6"><a href="{% url 'users:logout' %}">Logout</a></li>
        {% else %}
            <li class="nav_li"><a href="{% url 'users:login' %}">Login</a></li>
            <li class="nav_li ml-6"><a href="{% url 'users:signup' %}">Sign Up</a></li>
        {% endif %}
    </ul>
</header>

templates/partials/messages.html
{% if messages %}
    <ul class="absolute mx-auto left-10 top-10">
        {% for message in messages %}
            <li class="messages font-medium bg-gray-700 rounded-full text-white py-4 px-6 w-64 text-center {% if message.tags %}{{message.tags}}{% endif %}">{{message}}</li>
        {% endfor %}            
    </ul>
{% endif %}
    