comments/urls.py
from django.urls import path
from .views import WriteCommentView, UpdateCommentView, comment_delete

app_name = "comments"

urlpatterns = [
    path("<int:pk>/write/", WriteCommentView.as_view(), name="write"),
    path(
        "<int:post_pk>/update/<int:comment_pk>",
        UpdateCommentView.as_view(),
        name="update",
    ),
    path("<int:post_pk>/delete/<int:comment_pk>", comment_delete, name="delete"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("posts/", include("posts.urls", namespace="posts")),
    path("users/", include("users.urls", namespace="users")),
    path("comments/", include("comments.urls", namespace="comments")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from posts import views as post_views

app_name = "core"

urlpatterns = [
    # path("", post_views.all_posts, name="home"),
    path("", post_views.HomeView.as_view(), name="home"),
]

comments/models.py
from django.db import models
from core import models as core_models
from users import models as user_models
from posts import models as post_models


class Comment(core_models.TimeStampedModel):

    """Comment Model Definition"""

    post_name = models.ForeignKey(
        post_models.Post, related_name="post_comments", on_delete=models.CASCADE
    )
    author_name = models.ForeignKey(
        user_models.User, related_name="author_comments", on_delete=models.CASCADE
    )
    comment_text = models.TextField()

    def __str__(self):
        return self.comment_text

comments/forms.py
from django import forms
from .models import Comment
from users.models import User
from posts.models import Post


class WriteCommentForm(forms.ModelForm):

    """WriteCommentForm Definition"""

    class Meta:
        model = Comment
        fields = ("comment_text",)

    def save(self, user_pk, post_pk, *args, **kwargs):
        comment = super().save(commit=False)
        author = User.objects.get(pk=user_pk)
        post = Post.objects.get(pk=post_pk)
        comment.author_name = author
        comment.post_name = post
        comment.save()

comments/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http.response import Http404
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import FormView, UpdateView

from users import mixins as user_mixins

from .forms import WriteCommentForm
from .models import Comment


class WriteCommentView(user_mixins.LoggedInOnlyView, FormView):

    """WriteCommentView Definition"""

    template_name = "comments/comment_write.html"
    form_class = WriteCommentForm

    def form_valid(self, form):
        user_pk = self.request.user.pk
        post_pk = self.kwargs.get("pk")
        form.save(user_pk, post_pk)
        messages.success(self.request, "Comment Uploaded!")
        return redirect(reverse("posts:detail", kwargs={"pk": post_pk}))


class UpdateCommentView(user_mixins.LoggedInOnlyView, UpdateView):

    """Update Comment Definition"""

    model = Comment
    template_name = "comments/comment_edit.html"
    fields = ("comment_text",)
    pk_url_kwarg = "comment_pk"

    def get_success_url(self):
        post_pk = self.kwargs.get("post_pk")
        return reverse("posts:detail", kwargs={"pk": post_pk})

    def post(self, request, *args: str, **kwargs):
        messages.success(self.request, "Comment Updated!")
        return super().post(request, *args, **kwargs)

    def get_object(self, queryset=None):
        comment = super().get_object(queryset=queryset)
        if comment.author_name.pk != self.request.user.pk:
            raise Http404()
        return comment


@login_required
def comment_delete(request, post_pk, comment_pk):
    """Delete Comment Definition"""

    try:
        comment = Comment.objects.get(pk=comment_pk)
        if comment.author_name.pk != request.user.pk:
            messages.error(request, "Can't delete that comment")
        else:
            comment.delete()
            messages.success(request, "Comment Deleted!")
            return redirect(reverse("posts:detail", kwargs={"pk": post_pk}))
    except Comment.DoesNotExist:
        return redirect(reverse("posts:detail", kwargs={"pk": post_pk}))

templates/comments/comment_edit.html
{% extends 'base.html' %}
    {% block contents %}
        <div class="p-6 container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border border-gray-400">
            {% include 'mixins/post/post_form.html' with form=form cta="Update Comment" %}
        </div>
    {% endblock contents %}
        

templates/comments/comment_list.html
<div>
    {% if user.is_authenticated %}
        <a href="{% url 'comments:write' post_pk %}"><span class="text-lg font-medium text-blue-700 border-green-800">Write a comment</span></a>
    {% endif %}
    <ul class="mb-10">
        {% for comment in comments %}
            <li class="border-t-2 mt-3 pt-3">
                <div class="flex items-center">
                    {% include "mixins/user_avartar.html" with user=comment.author_name h_and_w='w-10 h-10' %}
                    <span class="ml-3 text-lg font-medium">{{comment.author_name.first_name}}</span>
                    {% if user == comment.author_name %}
                        <a href="{% url 'comments:update' post_pk=post_pk comment_pk=comment.pk %}"><span class="ml-3 font-medium bg-yellow-500 text-white p-1 rounded-lg">Edit</span></a>
                        <a href="{% url 'comments:delete' post_pk=post_pk comment_pk=comment.pk %}"><span class="ml-3 font-medium bg-red-500 text-white p-1 rounded-lg">Delete</span></a>
                    {% endif %}
                </div>
                <p class="my-3">
                    {{comment}}
                </p>
                <span class="text-light text-gray-500">{{comment.created|date:'Y-m-d H:i'}}</span>
            </li>
        {% endfor %}
    </ul>
</div>

templates/comments/comment_write.html
{% extends 'base.html' %}
    {% block contents %}
        <div class="p-6 container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border border-gray-400">
            {% include 'mixins/post/post_form.html' with form=form cta="Write Comment" %}
        </div>
    {% endblock contents %}
        