config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("posts/", include("posts.urls", namespace="posts")),
    path("users/", include("users.urls", namespace="users")),
    path("comments/", include("comments.urls", namespace="comments")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from posts import views as post_views

app_name = "core"

urlpatterns = [
    # path("", post_views.all_posts, name="home"),
    path("", post_views.HomeView.as_view(), name="home"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
]

users/models.py
# from django.contrib.auth.models import User
# from collections.abc import Iterable
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls.base import reverse
from PIL import Image


class Profile(models.Model):
    # user = models.OneToOneField("User", on_delete=models.CASCADE)
    user = models.ForeignKey("User", on_delete=models.CASCADE)
    avatar = models.ImageField(default="default.jpg", upload_to="avatar")

    # def __str__(self):
    #     return f"{self.user.username} Profile"

    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)

        img = Image.open(self.avatar.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.avatar.path)


class User(AbstractUser):
    # profile = models.OneToOneField(Profile, on_delete=models.CASCADE)
    # profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    """User Model Definition"""

    GENDER_MALE = "male"
    GENDER_FEMALE = "female"

    GENDER_CHOICES = (
        (GENDER_MALE, "Male"),
        (GENDER_FEMALE, "Female"),
    )

    # first_name = models.CharField(max_length=100)
    # second_name = models.CharField(max_length=100)
    # avatar = models.ImageField(upload_to="avatar", null=True, blank=True)
    username = models.CharField(max_length=100, unique=True)
    email = models.EmailField()
    gender = models.CharField(
        choices=GENDER_CHOICES, max_length=10, null=True, blank=True
    )
    bio = models.TextField(default="", blank=True)
    superhost = models.BooleanField(default=False)

    # def get_absolute_url(self):
    #     return reverse("users:profile", kwargs={"pk": self.pk})

users/forms.py
from django import forms
from django.contrib.auth.forms import PasswordChangeForm
from django.forms import widgets
from django.forms.fields import EmailField
from django.forms.widgets import EmailInput, TextInput

from . import models


class LoginForm(forms.Form):

    """Login Form Definition"""

    email = forms.EmailField(widget=forms.EmailInput(attrs={"placeholder": "Email"}))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Password"})
    )

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")

        try:
            user = models.User.objects.get(username=email)
            if user.check_password(password):
                return self.cleaned_data
            else:
                self.add_error("password", forms.ValidationError("Password is wrong"))
        except models.User.DoesNotExist:
            self.add_error("email", forms.ValidationError("User does not exist"))


class SignUpForm(forms.Form):
    first_name = forms.CharField(
        max_length=80, widget=forms.TextInput(attrs={"placeholder": "First Name"})
    )
    last_name = forms.CharField(
        max_length=80, widget=forms.TextInput(attrs={"placeholder": "Last Name"})
    )
    email = forms.EmailField(widget=EmailInput(attrs={"placeholder": "Email"}))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Password"})
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Confirm Password"})
    )

    def clean_email(self):
        email = self.cleaned_data.get("email")
        try:
            models.User.objects.get(email=email)
            raise forms.ValidationError("User already exists with that email")
        except models.User.DoesNotExist:
            return email

    def clean_password1(self):
        password = self.cleaned_data.get("password")
        password1 = self.cleaned_data.get("password1")

        if password != password1:
            raise forms.ValidationError("Password Confirmation does not match")
        else:
            return password

    def save(self):
        first_name = self.cleaned_data.get("first_name")
        last_name = self.cleaned_data.get("last_name")
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")

        user = models.User.objects.create_user(email, email, password)
        user.first_name = first_name
        user.last_name = last_name
        user.save()


class UpdatePasswordForm(PasswordChangeForm):

    """Update Password Form Definition"""

    old_password = forms.CharField(
        required=True,
        widget=forms.PasswordInput(
            attrs={"placeholder": "Current Password", "class": "rounded-lg"}
        ),
    )

    new_password1 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(
            attrs={"placeholder": "New Password", "class": "rounded-lg"}
        ),
    )

    new_password2 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(
            attrs={"placeholder": "Confirm New Password", "class": "rounded-lg"}
        ),
    )


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = models.Profile
        fields = ["avatar"]

users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.views import PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin
from django.db import models
from django.shortcuts import redirect, render
from django.urls import reverse
from django.urls.base import clear_script_prefix, reverse_lazy
from django.views import View
from django.views.generic import DetailView, FormView, UpdateView

from . import forms, mixins, models


class LoginView(mixins.LoggedOutOnlyView, View):
    def get(self, request):
        form = forms.LoginForm(initial={"email": "admin@admin.com"})
        return render(request, "users/login.html", {"form": form})

    def post(self, request):
        form = forms.LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get("email")
            password = form.cleaned_data.get("password")
            user = authenticate(request, username=email, password=password)
            if user is not None:
                messages.success(request, f"Welcome back {user.first_name}")
                login(self.request, user)
                return redirect(reverse("core:home"))
        return render(request, "users/login.html", {"form": form})


def log_out(request):
    messages.info(request, "See you later")
    logout(request)
    return redirect(reverse("core:home"))


class SignUpView(mixins.LoggedOutOnlyView, FormView):
    template_name = "users/signup.html"
    form_class = forms.SignUpForm
    success_url = reverse_lazy("core:home")
    initial = {
        "first_name": "Jiho",
        "last_name": "Ju",
        "email": "jiho@jiho.com",
    }

    def form_valid(self, form):
        form.save()
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            messages.success(self.request, f"Welcome!! {user.first_name}")
            login(self.request, user)
        return super().form_valid(form)


class UserProfileView(DetailView):

    """UserProfileView Definition"""

    model = models.User
    context_object_name = "user_obj"
    template_name = "users/user_profile.html"


class UpdateProfileView(mixins.LoggedInOnlyView, SuccessMessageMixin, UpdateView):

    """UserProfileUpdate View Definition"""

    model = models.User
    template_name = "users/update-profile.html"
    fields = (
        "first_name",
        "last_name",
        # "avatar",
        "gender",
        "bio",
        "superhost",
    )
    success_message = "Profile Updated"

    def get_object(self, queryset=None):
        return self.request.user

    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)
        return form

    def get_success_url(self):
        pk = self.request.user.pk
        return reverse("users:profile", kwargs={"pk": pk})
        # return self.request.user.get_absolute_url() => 이렇게 User model에서 get_absolute_url를 정의해서 사용할 수 있당~


class UpdatePasswordView(
    mixins.LoggedInOnlyView, SuccessMessageMixin, PasswordChangeView
):

    """UpdatePasswordView Definition"""

    model = models.User
    template_name = "users/update-password.html"
    form_class = forms.UpdatePasswordForm
    success_message = "Password Updated"
    success_url = reverse_lazy("core:home")

templates/users/login.html
{% extends 'base.html' %}

{% block page_title %}
    Log In
{% endblock page_title %}

{% block contents %}    
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-200">
        {% include 'mixins/auth/auth_form.html' with form=form cta="Log In" %}
        <div class="flex flex-col justify-center items-center mt-3">
            <span class="text-xl">Don't have an account?</span>
            <a href="{% url 'users:signup' %}" class="text-2xl font-medium text-purple-600">Sign Up</a>
        </div>
    </div>
{% endblock contents %}
    
    

templates/users/signup.html
{% extends 'base.html' %}

{% block page_title %}
    Sign Up
{% endblock page_title %}

{% block contents %}
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-300">
        {% include "mixins/auth/auth_form.html" with form=form cta="Sign Up" %}
    </div>

{% endblock contents %}
    
    

templates/users/update-password.html
{% extends 'base.html' %}

{% block page_title %}
    Change Password
{% endblock page_title %}

{% block contents %}    
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-200">
        {% include "mixins/auth/auth_form.html" with form=form cta="Change Password" %}
    </div>
{% endblock contents %}
    
    

templates/users/update-profile.html
{% extends 'base.html' %}

{% block page_title %}
    Update Profile
{% endblock page_title %}

{% block contents %}
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-200">
        {% include "mixins/auth/auth_form.html" with form=form cta="Update Profile" %}
    </div>
{% endblock contents %}

templates/users/user_profile.html
{% extends 'base.html' %}

{% block page_title %}
    {{user_obj.first_name}}'s Profile
{% endblock page_title %}

{% block contents %}
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-200">
        {% include "mixins/user_avartar.html" with user=user_obj %}
        <div class="flex items-center justify-center">
            <span class="text-3xl mt-1">{{user_obj.first_name}}</span>
            {% if user_obj.superhost %}
                <i class=" text-yellow-400 fas fa-check-circle fa-lg ml-1"></i>
            {% endif %}
        </div>
        <span class="text-lg mb-5">{{user_obj.bio}}</span>

        {% if user_obj == user %}
            <a href="{% url 'users:update' %}" class="btn bg-red-400 text-white">Update Profile</a>
            <div class="mt-2 rounded-md bg-green-500 text-white w-full text-center py-5">
                <a href="{% url 'users:password' %}" class="font-medium text-lg">Change Password</a>
            </div>
        {% endif %}
    </div>
{% endblock contents %}